### ISSUE TITLE
Allow different remote url other than godbolt.org

### ISSUE THREAD

**Issue by AbrilRBS** [ethanhs/cce#1]
CE is selfhosted by some users. I think they would appreciate if there was a way to specify other remote url. Maybe even an IP to use a local instance! :)

**Comment by emmatyping** [comment]
This makes a lot of sense. I will work on this today. (Currently adding support for passing a file)

**Comment by dkm** [comment]
Would love that. My simple hack consisting on a sed pass failed. Not sure why, but I get : 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Json(Error("missing field `text`", line: 1, column: 663)), url: None }', libcore/result.rs:945:5
```

Listings the compilers works correcly. Any hint welcome :)

**Comment by dkm** [comment]
For my internal use, I've added a `--host` that defaults to godbolt.org. Do you want me to submit a PR ?

**Comment by emmatyping** [comment]
That would be great! Thank you

**Comment by dkm** [comment]
Ok, so I'll clean my code and push a PR asap !

**Comment by emmatyping** [comment]
@dkm, looking forward to your pr! :)
