### ISSUE TITLE
Raw asm output

### ISSUE THREAD

**Issue by davidbolvansky** [ethanhs/cce#2]
Can you add option to get raw asm output? (no "Compiling with" line)
https://github.com/ethanhs/cce/blob/master/src/main.rs#L92

**Comment by emmatyping** [comment]
I think I will just remove it. It is a nice visual cue, but I don't think it is super needed, and it makes it hard to compose with other command line tools.

**Comment by davidbolvansky** [comment]
Thanks

**Comment by davidbolvansky** [comment]
I built in and... why it has 8.6 MB? :D

**Comment by emmatyping** [comment]
Did you do a release build? It might not have removed some debugging information.

**Comment by davidbolvansky** [comment]
Yes. cargo build --release

after strip cce - 3.2 MB.

**Comment by emmatyping** [comment]
It seems to be 3,068,416 bytes on Windows, and after the lto I just enabled, 2,852,864 bytes. Rust will link in everything statically, so 3MB isn't *that* big.

**Comment by davidbolvansky** [comment]
Yes yes, for static build 3MB is fine.
