### ISSUE TITLE
Get an URL

### ISSUE THREAD

**Issue by dkm** [ethanhs/cce#3]
As stated in https://github.com/mattgodbolt/compiler-explorer/issues/938 , I would like to get an URL for a corresponding compilation job. I've already have something written in python, but having this included in a rich cli tool would be even better for our usecase.

I've already started to hack this, but it seems I can't get the tool to work correctly with my self-hosted CE.

**Comment by dkm** [comment]
FYI, I've got a first working prototype. I need to add some error handling, but basic URL creation works. I'll push a PR next week :)

**Comment by emmatyping** [comment]
Fixed in #4
